# from PreResNet import *
from .NetworkInNetwork import *
from .LeNet import *
from .vgg_cifar import *
from .vgg_gap import *
from .PreResNet_test import *
from .PreResNetScalar import *
from .MobilenetV2 import *
from .AlexNetBN import *
from .AlexNetBNCifar import *
from .MobilenetCifar import *
from .MobilenetV2 import *
from .MobilenetV1 import *
from .ThinMobilenetV1 import *
from .MobilenetV2Cifar import *
from .Mobilenet import *
from .QuanResNet import *
from .ResNetCifar import *
from .QuanResNetCifar import *